version: 2

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error
