run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - goimports
  disable:
    - typecheck
    - gocritic
    - gocyclo
    - goconst
    - gocognit
    - gomnd
    - gosec
    - interfacer
    - maligned
    - prealloc
    - scopelint
    - structcheck
    - varcheck
    - deadcode
    - dupl
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - godot
    - godox
    - golint
    - lll
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
    - wsl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error
