package soc2

import (
	"time"
)

// GetDefaultEnterpriseReadinessConfig returns the default enterprise readiness configuration
func GetDefaultEnterpriseReadinessConfig() *EnterpriseReadinessConfig {
	return &EnterpriseReadinessConfig{
		ComplianceRequirements: []ComplianceRequirement{
			{
				ID:             "soc2_cc1",
				Name:           "Control Environment",
				Description:    "Establish and maintain a control environment that supports the achievement of the entity's objectives",
				Category:       "Security",
				Priority:       "high",
				Status:         "implemented",
				Implementation: "Implemented through organizational structure, policies, and procedures",
				Evidence: []string{
					"Organizational chart",
					"Code of conduct",
					"Ethics policy",
					"Management oversight procedures",
				},
				LastReviewed: time.Now().Add(-30 * 24 * time.Hour),
				NextReview:   time.Now().Add(30 * 24 * time.Hour),
				Owner:        "compliance_team",
				Metadata: map[string]interface{}{
					"regulation": "SOC 2",
					"control_id": "CC1",
				},
			},
			{
				ID:             "soc2_cc2",
				Name:           "Communication and Information",
				Description:    "Communicate information to enable all personnel to understand and carry out their internal control responsibilities",
				Category:       "Security",
				Priority:       "high",
				Status:         "implemented",
				Implementation: "Implemented through training programs, documentation, and communication channels",
				Evidence: []string{
					"Training records",
					"Communication policies",
					"Documentation system",
					"Incident reporting procedures",
				},
				LastReviewed: time.Now().Add(-30 * 24 * time.Hour),
				NextReview:   time.Now().Add(30 * 24 * time.Hour),
				Owner:        "compliance_team",
				Metadata: map[string]interface{}{
					"regulation": "SOC 2",
					"control_id": "CC2",
				},
			},
			{
				ID:             "soc2_cc3",
				Name:           "Risk Assessment",
				Description:    "Identify and analyze risks to the achievement of objectives",
				Category:       "Security",
				Priority:       "high",
				Status:         "implemented",
				Implementation: "Implemented through risk assessment procedures and monitoring",
				Evidence: []string{
					"Risk assessment reports",
					"Risk register",
					"Risk monitoring procedures",
					"Risk mitigation plans",
				},
				LastReviewed: time.Now().Add(-30 * 24 * time.Hour),
				NextReview:   time.Now().Add(30 * 24 * time.Hour),
				Owner:        "risk_management_team",
				Metadata: map[string]interface{}{
					"regulation": "SOC 2",
					"control_id": "CC3",
				},
			},
			{
				ID:             "soc2_cc4",
				Name:           "Monitoring Activities",
				Description:    "Monitor the system and take corrective action when necessary",
				Category:       "Security",
				Priority:       "high",
				Status:         "implemented",
				Implementation: "Implemented through monitoring tools and procedures",
				Evidence: []string{
					"Monitoring reports",
					"Alert logs",
					"Corrective action records",
					"Performance metrics",
				},
				LastReviewed: time.Now().Add(-30 * 24 * time.Hour),
				NextReview:   time.Now().Add(30 * 24 * time.Hour),
				Owner:        "operations_team",
				Metadata: map[string]interface{}{
					"regulation": "SOC 2",
					"control_id": "CC4",
				},
			},
			{
				ID:             "soc2_cc5",
				Name:           "Control Activities",
				Description:    "Design and implement control activities to mitigate risks",
				Category:       "Security",
				Priority:       "high",
				Status:         "implemented",
				Implementation: "Implemented through access controls, segregation of duties, and approval processes",
				Evidence: []string{
					"Access control matrix",
					"Segregation of duties documentation",
					"Approval workflows",
					"Control testing results",
				},
				LastReviewed: time.Now().Add(-30 * 24 * time.Hour),
				NextReview:   time.Now().Add(30 * 24 * time.Hour),
				Owner:        "security_team",
				Metadata: map[string]interface{}{
					"regulation": "SOC 2",
					"control_id": "CC5",
				},
			},
		},
		SecurityControls: []SecurityControl{
			{
				ID:             "access_control",
				Name:           "Access Control",
				Description:    "Implement and maintain access controls to protect system resources",
				ControlType:    "preventive",
				Implementation: "Role-based access control with multi-factor authentication",
				Status:         "implemented",
				Effectiveness:  "effective",
				LastTested:     time.Now().Add(-7 * 24 * time.Hour),
				NextTest:       time.Now().Add(7 * 24 * time.Hour),
				Owner:          "security_team",
				Metadata: map[string]interface{}{
					"control_family": "access_control",
					"nist_framework": "AC",
				},
			},
			{
				ID:             "encryption",
				Name:           "Data Encryption",
				Description:    "Encrypt data at rest and in transit",
				ControlType:    "preventive",
				Implementation: "AES-256 encryption for data at rest, TLS 1.3 for data in transit",
				Status:         "implemented",
				Effectiveness:  "effective",
				LastTested:     time.Now().Add(-7 * 24 * time.Hour),
				NextTest:       time.Now().Add(7 * 24 * time.Hour),
				Owner:          "security_team",
				Metadata: map[string]interface{}{
					"control_family": "encryption",
					"nist_framework": "SC",
				},
			},
			{
				ID:             "monitoring",
				Name:           "Security Monitoring",
				Description:    "Monitor system for security events and anomalies",
				ControlType:    "detective",
				Implementation: "SIEM system with real-time alerting",
				Status:         "implemented",
				Effectiveness:  "effective",
				LastTested:     time.Now().Add(-7 * 24 * time.Hour),
				NextTest:       time.Now().Add(7 * 24 * time.Hour),
				Owner:          "security_team",
				Metadata: map[string]interface{}{
					"control_family": "monitoring",
					"nist_framework": "SI",
				},
			},
			{
				ID:             "incident_response",
				Name:           "Incident Response",
				Description:    "Respond to security incidents in a timely manner",
				ControlType:    "corrective",
				Implementation: "Incident response team with defined procedures",
				Status:         "implemented",
				Effectiveness:  "effective",
				LastTested:     time.Now().Add(-30 * 24 * time.Hour),
				NextTest:       time.Now().Add(30 * 24 * time.Hour),
				Owner:          "security_team",
				Metadata: map[string]interface{}{
					"control_family": "incident_response",
					"nist_framework": "IR",
				},
			},
		},
		AvailabilityTargets: AvailabilityTargets{
			UptimeTarget:       0.999, // 99.9% uptime
			ResponseTimeTarget: 2 * time.Second,
			RecoveryTimeTarget: 4 * time.Hour,
			DataLossTarget:     1 * time.Hour,
			MonitoringEnabled:  true,
			AlertingEnabled:    true,
			BackupEnabled:      true,
			Metadata: map[string]interface{}{
				"target_type":   "enterprise",
				"service_level": "premium",
			},
		},
		DataProtectionRules: []DataProtectionRule{
			{
				ID:              "personal_data",
				Name:            "Personal Data Protection",
				Description:     "Protect personal data according to GDPR and other privacy regulations",
				RuleType:        "privacy",
				DataTypes:       []string{"personal_data", "sensitive_data"},
				RetentionPeriod: 7 * 365 * 24 * time.Hour, // 7 years
				Encryption:      true,
				AccessControl:   true,
				AuditLogging:    true,
				Status:          "implemented",
				Metadata: map[string]interface{}{
					"regulation":          "GDPR",
					"data_classification": "sensitive",
				},
			},
			{
				ID:              "financial_data",
				Name:            "Financial Data Protection",
				Description:     "Protect financial data according to PCI-DSS requirements",
				RuleType:        "security",
				DataTypes:       []string{"financial_data", "payment_data"},
				RetentionPeriod: 3 * 365 * 24 * time.Hour, // 3 years
				Encryption:      true,
				AccessControl:   true,
				AuditLogging:    true,
				Status:          "implemented",
				Metadata: map[string]interface{}{
					"regulation":          "PCI-DSS",
					"data_classification": "confidential",
				},
			},
			{
				ID:              "audit_data",
				Name:            "Audit Data Protection",
				Description:     "Protect audit data and maintain audit trail integrity",
				RuleType:        "compliance",
				DataTypes:       []string{"audit_data", "log_data"},
				RetentionPeriod: 7 * 365 * 24 * time.Hour, // 7 years
				Encryption:      true,
				AccessControl:   true,
				AuditLogging:    true,
				Status:          "implemented",
				Metadata: map[string]interface{}{
					"regulation":          "SOC 2",
					"data_classification": "audit",
				},
			},
		},
		IncidentResponsePlan: IncidentResponsePlan{
			ID:          "incident_response_plan_v1",
			Name:        "Security Incident Response Plan",
			Description: "Comprehensive plan for responding to security incidents",
			ResponseTeam: []ResponseTeamMember{
				{
					ID:   "incident_commander",
					Name: "John Smith",
					Role: "Incident Commander",
					ContactInfo: ContactInfo{
						Email:            "john.smith@company.com",
						Phone:            "+1-555-0101",
						Mobile:           "+1-555-0102",
						EmergencyContact: "+1-555-0103",
					},
					Availability: "24/7",
					Skills:       []string{"incident_management", "security_analysis", "communication"},
					Metadata:     make(map[string]interface{}),
				},
				{
					ID:   "security_analyst",
					Name: "Jane Doe",
					Role: "Security Analyst",
					ContactInfo: ContactInfo{
						Email:            "jane.doe@company.com",
						Phone:            "+1-555-0201",
						Mobile:           "+1-555-0202",
						EmergencyContact: "+1-555-0203",
					},
					Availability: "business_hours",
					Skills:       []string{"security_analysis", "forensics", "threat_hunting"},
					Metadata:     make(map[string]interface{}),
				},
			},
			EscalationPath: []EscalationLevel{
				{
					ID:           "level_1",
					Level:        1,
					Name:         "Initial Response",
					Description:  "Initial incident response and assessment",
					Trigger:      "Security incident detected",
					ResponseTime: 15 * time.Minute,
					Contacts: []ContactInfo{
						{
							Email: "security@company.com",
							Phone: "+1-555-0301",
						},
					},
					Metadata: make(map[string]interface{}),
				},
				{
					ID:           "level_2",
					Level:        2,
					Name:         "Management Escalation",
					Description:  "Escalate to management for significant incidents",
					Trigger:      "High severity incident or Level 1 escalation",
					ResponseTime: 1 * time.Hour,
					Contacts: []ContactInfo{
						{
							Email: "management@company.com",
							Phone: "+1-555-0401",
						},
					},
					Metadata: make(map[string]interface{}),
				},
			},
			CommunicationPlan: CommunicationPlan{
				ID:          "communication_plan_v1",
				Name:        "Incident Communication Plan",
				Description: "Plan for communicating during security incidents",
				Channels: []CommunicationChannel{
					{
						ID:           "email",
						Name:         "Email",
						Type:         "electronic",
						Description:  "Primary communication channel",
						Availability: "24/7",
						Metadata:     make(map[string]interface{}),
					},
					{
						ID:           "phone",
						Name:         "Phone",
						Type:         "voice",
						Description:  "Emergency communication channel",
						Availability: "24/7",
						Metadata:     make(map[string]interface{}),
					},
				},
				Templates: []CommunicationTemplate{
					{
						ID:         "incident_notification",
						Name:       "Incident Notification",
						Type:       "notification",
						Subject:    "Security Incident Notification",
						Body:       "A security incident has been detected and is being investigated.",
						Recipients: []string{"security@company.com", "management@company.com"},
						Metadata:   make(map[string]interface{}),
					},
				},
				EscalationRules: []EscalationRule{
					{
						ID:          "escalation_rule_1",
						Name:        "High Severity Escalation",
						Description: "Escalate high severity incidents immediately",
						Condition:   "severity = high",
						Action:      "notify_management",
						Timeout:     30 * time.Minute,
						Metadata:    make(map[string]interface{}),
					},
				},
				Metadata: make(map[string]interface{}),
			},
			RecoveryProcedures: []RecoveryProcedure{
				{
					ID:            "data_breach_recovery",
					Name:          "Data Breach Recovery",
					Description:   "Procedures for recovering from a data breach",
					ProcedureType: "recovery",
					Steps: []string{
						"Assess the scope of the breach",
						"Contain the breach",
						"Notify affected parties",
						"Implement additional security measures",
						"Monitor for further incidents",
					},
					EstimatedTime: 24 * time.Hour,
					Prerequisites: []string{"incident_response_team", "legal_counsel"},
					Metadata:      make(map[string]interface{}),
				},
			},
			TestingSchedule: 90 * 24 * time.Hour, // 90 days
			LastTested:      time.Now().Add(-30 * 24 * time.Hour),
			NextTest:        time.Now().Add(60 * 24 * time.Hour),
			Metadata:        make(map[string]interface{}),
		},
		BusinessContinuityPlan: BusinessContinuityPlan{
			ID:            "business_continuity_plan_v1",
			Name:          "Business Continuity Plan",
			Description:   "Plan for maintaining business operations during disruptions",
			RecoveryTime:  4 * time.Hour,
			RecoveryPoint: 1 * time.Hour,
			BackupStrategy: BackupStrategy{
				ID:              "backup_strategy_v1",
				Name:            "Data Backup Strategy",
				Description:     "Comprehensive data backup and recovery strategy",
				BackupFrequency: 24 * time.Hour,
				RetentionPeriod: 30 * 24 * time.Hour,
				BackupLocation:  "secure_cloud_storage",
				Encryption:      true,
				TestingSchedule: 30 * 24 * time.Hour,
				Metadata:        make(map[string]interface{}),
			},
			DisasterRecovery: DisasterRecovery{
				ID:              "disaster_recovery_v1",
				Name:            "Disaster Recovery Plan",
				Description:     "Plan for recovering from major disasters",
				RecoverySite:    "secondary_data_center",
				RecoveryTime:    8 * time.Hour,
				RecoveryPoint:   2 * time.Hour,
				TestingSchedule: 180 * 24 * time.Hour, // 180 days
				Metadata:        make(map[string]interface{}),
			},
			TestingSchedule: 180 * 24 * time.Hour, // 180 days
			LastTested:      time.Now().Add(-60 * 24 * time.Hour),
			NextTest:        time.Now().Add(120 * 24 * time.Hour),
			Metadata:        make(map[string]interface{}),
		},
		VendorManagement: VendorManagement{
			ID:          "vendor_management_v1",
			Name:        "Vendor Management Program",
			Description: "Program for managing third-party vendors and suppliers",
			Vendors: []Vendor{
				{
					ID:               "vendor_1",
					Name:             "Cloud Provider",
					Type:             "infrastructure",
					Description:      "Primary cloud infrastructure provider",
					RiskLevel:        "medium",
					ComplianceStatus: "compliant",
					LastAssessment:   time.Now().Add(-90 * 24 * time.Hour),
					NextAssessment:   time.Now().Add(90 * 24 * time.Hour),
					ContactInfo: ContactInfo{
						Email: "vendor@cloudprovider.com",
						Phone: "+1-555-1001",
					},
					Metadata: make(map[string]interface{}),
				},
				{
					ID:               "vendor_2",
					Name:             "Security Provider",
					Type:             "security",
					Description:      "Security monitoring and incident response provider",
					RiskLevel:        "low",
					ComplianceStatus: "compliant",
					LastAssessment:   time.Now().Add(-60 * 24 * time.Hour),
					NextAssessment:   time.Now().Add(120 * 24 * time.Hour),
					ContactInfo: ContactInfo{
						Email: "security@securityprovider.com",
						Phone: "+1-555-2001",
					},
					Metadata: make(map[string]interface{}),
				},
			},
			AssessmentSchedule: 90 * 24 * time.Hour, // 90 days
			LastAssessment:     time.Now().Add(-30 * 24 * time.Hour),
			NextAssessment:     time.Now().Add(60 * 24 * time.Hour),
			Metadata:           make(map[string]interface{}),
		},
		RiskManagement: RiskManagement{
			ID:          "risk_management_v1",
			Name:        "Risk Management Program",
			Description: "Comprehensive risk management program",
			RiskAssessment: RiskAssessment{
				ID:             "risk_assessment_v1",
				Name:           "Enterprise Risk Assessment",
				Description:    "Assessment of enterprise-wide risks",
				RiskLevel:      "medium",
				Impact:         "medium",
				Likelihood:     "low",
				RiskScore:      0.25,
				LastAssessed:   time.Now().Add(-30 * 24 * time.Hour),
				NextAssessment: time.Now().Add(90 * 24 * time.Hour),
				Metadata:       make(map[string]interface{}),
			},
			RiskMitigation: []RiskMitigation{
				{
					ID:             "mitigation_1",
					Name:           "Security Controls",
					Description:    "Implement comprehensive security controls",
					MitigationType: "preventive",
					Effectiveness:  "high",
					Cost:           50000.0,
					Implementation: "Implemented through security framework",
					Status:         "implemented",
					Metadata:       make(map[string]interface{}),
				},
				{
					ID:             "mitigation_2",
					Name:           "Monitoring and Alerting",
					Description:    "Implement monitoring and alerting systems",
					MitigationType: "detective",
					Effectiveness:  "high",
					Cost:           25000.0,
					Implementation: "Implemented through SIEM system",
					Status:         "implemented",
					Metadata:       make(map[string]interface{}),
				},
			},
			RiskMonitoring: RiskMonitoring{
				ID:             "risk_monitoring_v1",
				Name:           "Risk Monitoring System",
				Description:    "Continuous monitoring of enterprise risks",
				MonitoringType: "continuous",
				Frequency:      24 * time.Hour,
				Thresholds: []MonitoringThreshold{
					{
						ID:        "threshold_1",
						Name:      "High Risk Threshold",
						Metric:    "risk_score",
						Threshold: 0.7,
						Operator:  "greater_than",
						Severity:  "high",
						Metadata:  make(map[string]interface{}),
					},
				},
				AlertingEnabled: true,
				Metadata:        make(map[string]interface{}),
			},
			ReviewSchedule: 90 * 24 * time.Hour, // 90 days
			LastReview:     time.Now().Add(-30 * 24 * time.Hour),
			NextReview:     time.Now().Add(60 * 24 * time.Hour),
			Metadata:       make(map[string]interface{}),
		},
		Metadata: map[string]interface{}{
			"version":    "1.0.0",
			"created_at": "2024-01-01T00:00:00Z",
			"updated_at": "2024-01-01T00:00:00Z",
		},
	}
}
